{{ config(materialized='ephemeral') }}
SELECT
    DISTINCT MCB.CATEGORY_ID,
    MCT.DESCRIPTION         CATEGORY_NAME,
    MCB.SEGMENT1            CAT_LEVEL0,
    MCS.CATEGORY_SET_NAME   CAT_LEVEL1,
    MCS.CATEGORY_SET_NAME   MAJOR_CATNAME

FROM
    "FIVETRAN"."ORACLE_EBS_INV".MTL_ITEM_CATEGORIES    MIC,
    "FIVETRAN"."ORACLE_EBS_INV".MTL_CATEGORY_SETS_TL   MCS,
    "FIVETRAN"."ORACLE_EBS_INV".MTL_CATEGORIES_B       MCB,
    "FIVETRAN"."ORACLE_EBS_INV".MTL_CATEGORIES_TL      MCT
WHERE
    MIC.CATEGORY_SET_ID = MCS.CATEGORY_SET_ID
    AND MIC.CATEGORY_ID = MCB.CATEGORY_ID
    AND MIC.CATEGORY_ID = MCT.CATEGORY_ID 